### ISSUE TITLE
False Discovery Rate threshold computation fails silently

### ISSUE THREAD

**Issue by ne1s0n** [Biometris/statgenGWAS#4] opened 2021-04-13 14:40 UTC
As per title, when selecting fdr as threshold type the computation fails and the threshold is set to NA silently (I noticed the absence of threshold in Manhattan plot).

This can be reproduced from the very base example in the [package home](https://github.com/Biometris/statgenGWAS). If I change the invocation of runSingleTraitGwas to:

```
GWASDrops <- runSingleTraitGwas(gData = gDataDropsDedup,
                                trials = "Mur13W",
                                traits = c("grain.yield", "anthesis"), thrType = 'fdr')
```
the threshold is not computed (note the thrType = 'fdr' extra param).
This is verified taking a look at the thr field:

```
> GWASDrops$thr
$Mur13W
grain.yield    anthesis 
         NA          NA 
```
And obviously no line shows up in the plot.

If it's not a bug it should at least warn the user.

**Comment by BartJanvanRossum** [comment] 2021-04-22 09:48
This is not a bug. 
Because of how the fdr method works it is possible that a snp is marked as significant whereas a snp with a higher -10logp value is not significant (e.g. because it is close to a peak). Because of this no fixed value can be computed for the threshold and it cannot be shown in the plot either. 
I agree that it would be good to make this more clear in the documentation. I will add that to the to do list for the next release of the package

**Comment by BartJanvanRossum** [comment] 2021-08-05 15:09
In the latest release of the package the documentation has been updated to clarify the reason for a NA value for the threshold when using "fdf".

**Closed by BartJanvanRossum** 2021-08-05 15:09 UTC
